server:
  port: 8082
spring:
  application:
    name: covid-service

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka # Docker service name
  # instance:
  #   prefer-ip-address: true
  #   lease-renewal-interval-in-seconds: 5
  #   lease-expiration-duration-in-seconds: 10

logging:
  level:
    com.netflix.discovery: OFF
    org.springframework.cloud.netflix.eureka.http: ERROR
