# configuration file for countries app
server:
  port: 8081
spring:
  application:
    name: countries-service
eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka  # Docker service name
  # instance:
  #   prefer-ip-address: true
  #   lease-renewal-interval-in-seconds: 5
  #   lease-expiration-duration-in-seconds: 10