services:
  # Eureka Server - Service Discovery
  eureka-service:
    build:
      context: .
      dockerfile: eureka-service/Dockerfile
    ports:
      - "8761:8761"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 30s
      timeout: 3s
      retries: 3
    restart: always
    
  # Countries Service
  countries-service:
    build:
      context: .
      dockerfile: countries-service/Dockerfile
    ports:
      - "8081:8081"
    networks:
      - app-network
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-service:8761/eureka
    depends_on:
      eureka-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 30s
      timeout: 3s
      retries: 3
    restart: always

  # Covid Service
  covid-service:
    build:
      context: .
      dockerfile: covid-service/Dockerfile
    ports:
      - "8082:8082"
    networks:
      - app-network
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-service:8761/eureka
    depends_on:
      eureka-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/actuator/health"]
      interval: 30s
      timeout: 3s
      retries: 3
    restart: always

  # Aggregator Service
  aggregator-service:
    build:
      context: .
      dockerfile: aggregator-service/Dockerfile
    ports:
      - "8083:8083"
    networks:
      - app-network
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-service:8761/eureka
    depends_on:
      eureka-service:
        condition: service_healthy
      countries-service:
        condition: service_healthy
      covid-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/actuator/health"]
      interval: 30s
      timeout: 3s
      retries: 3
    restart: always

  # API Gateway
  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    ports:
      - "80:80"
    networks:
      - app-network
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-service:8761/eureka
    depends_on:
      eureka-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/actuator/health"]
      interval: 30s
      timeout: 3s
      retries: 3
    restart: always

networks:
  app-network:
    driver: bridge